language: ruby
cache: bundler
sudo: false
  
#

rvm:
  - &ruby1 2.3.0
  - &ruby2 2.2.4
  - &ruby3 2.1.8
  - &rhead ruby-head

#

matrix:
  fast_finish: true
  allow_failures:
    - rvm: *rhead

#

notifications:
  email:
    recipients:
      - adam@abemedia.co.uk

#

branches:
  only:
    - master

#
